version: "3.9"

services:

  backend:
    build: ./backend
    container_name: smartchange_backend
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - mongo
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: smartchange_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: smartchange
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  mongo:
    image: mongo:6
    container_name: smartchange_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  postgres_data:
  mongo_data: